chore: update automated-translations branch to 12.x.x

diff --git a/.github/workflows/cherry-pick.yml b/.github/workflows/cherry-pick.yml
--- a/.github/workflows/cherry-pick.yml
+++ b/.github/workflows/cherry-pick.yml
@@ -4,7 +4,7 @@ on:
     types:
       - closed
     branches:
-      - 11.x.x
+      - '[0-9]+.x.x'
 
 env:
   TARGET_BRANCH: main
@@ -20,23 +20,13 @@ jobs:
           ref: ${{ env.TARGET_BRANCH }}
           fetch-depth: 0
           token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
-
       - uses: actions/setup-node@v4
         id: setup-node
         with:
+          cache: 'npm'
           node-version-file: '.nvmrc'
-
-      - name: Cache node modules
-        id: cache
-        uses: actions/cache@v4
-        with:
-          path: node_modules
-          key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}
-
       - name: npm install
-        if: steps.cache.outputs.cache-hit != 'true'
         run: npm ci
-
       - name: Cherry pick
         id: cherry-pick
         run: |
@@ -59,6 +49,34 @@ jobs:
           if [ $? -ne 0 ]; then
             echo "CHERRY_PICK_RESULT=failed" >> $GITHUB_ENV
             exit 0
+          fi
+
+          # Capture @angular/core migrations.
+          FROM_VERSION=$(git cat-file --textconv origin/${{ env.FROM_BRANCH }}:package.json | jq -r '.dependencies["@angular/core"]')
+          TO_VERSION=$(jq -r '.dependencies["@angular/core"]' package.json)
+          npx nx migrate @angular/core \
+            --from="@angular/core@${FROM_VERSION}" \
+            --to="@angular/core@${TO_VERSION}"
+
+          # Remove migrations that are not needed for cherry-picks. They take too long to run and should not apply.
+          jq -r '.migrations | map(select(.name != "inject-flags")) | map(select(.name != "test-bed-get")) | {"migrations": .}' migrations.json >  migrations.json.tmp \
+            && mv migrations.json.tmp migrations.json
+
+          # Run the migrations and fix any formatting issues.
+          npx nx migrate --run-migrations --if-exists && npx nx format:write
+
+          if [ $? -ne 0 ]; then
+            echo "CHERRY_PICK_RESULT=failed" >> $GITHUB_ENV
+            exit 0
+          fi
+
+          rm -f ./migrations.json
+          # Any changes to package.json and package-lock.json should not be committed.
+          git restore package.json package-lock.json
+          git add -A
+          git status
+          if [ -n "$(git status --porcelain)" ]; then
+            git commit --amend --no-edit
           fi
 
           # Get the name of the cherry-pick branch.
@@ -101,21 +119,18 @@ jobs:
               console.log(`Created PR #${result.data.number}: ${result.data.html_url}`);
               core.exportVariable('PR_URL', result.data.html_url);
               core.exportVariable('CHERRY_PICK_RESULT', 'success');
-              const riskLabels = pr.labels.map(label => label.name).filter(label => label.startsWith('risk level'));
-              if (riskLabels.length === 0) {
-                if (pr.labels.find(label => label.name.startsWith('autorelease'))) {
-                  // Changelog PR, so add minimal risk level labels.
-                  riskLabels.push('risk level (author): 1', 'risk level (reviewer): 1');
-                } else {
-                  // No risk level label found, so don't add any.
-                  return;
-                }
+              const labels = pr.labels.map(label => label.name).filter(label => label.startsWith('risk level') || label === 'skip e2e');
+              const assignees = pr.user.login && pr.user.type === 'User' && pr.user.login !== 'blackbaud-sky-build-user' ? [pr.user.login] : [];
+              if (labels.length === 0 && pr.labels.find(label => label.name.startsWith('autorelease'))) {
+                // Changelog PR, so add minimal risk level labels.
+                labels.push('risk level (author): 1');
               }
               return github.rest.issues.update({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 issue_number: result.data.number,
-                labels: riskLabels
+                assignees: assignees,
+                labels: labels
               });
             }).catch(error => {
               console.log(error);
