ci: set percy target commit (#2063) (#2135)
* ci: set percy target commit

* Update cache settings, add additional output.

* Update lock file

* Test coverage

* Fix percy target branch for workflow dispatch

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -12,7 +12,10 @@ on:
 env:
   CYPRESS_VERIFY_TIMEOUT: 120000
   GH_PAGES_OWNER: blackbaud
+  PERCY_BRANCH: ${{ github.ref_name }}
   PERCY_BROWSER_EXECUTABLE: /usr/bin/chromium
+  PERCY_COMMIT: ${{ github.sha }}
+  PERCY_SKIP_UPDATE_CHECK: 'true'
   PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
   PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
   SB_CHROMIUM_PATH: /usr/bin/chromium
@@ -31,6 +34,7 @@ jobs:
       pr-number: ${{ steps.set-shas.outputs.pr-number }}
       pr-labels: ${{ steps.set-shas.outputs.pr-labels }}
       base: ${{ steps.set-shas.outputs.base }}
+      base-branch: ${{ steps.set-shas.outputs.base-branch }}
       head: ${{ steps.set-shas.outputs.head }}
     steps:
       - uses: actions/checkout@v4
@@ -302,31 +306,30 @@ jobs:
         run: npx cypress verify
         if: ${{ matrix.project != 'skip' && steps.affected.outputs.affected == 'true' }}
       - name: Percy ${{ matrix.project }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            // Timing setting recommended by https://docs.percy.io/docs/cypress#missing-assets
-            const percyCommand = 'npx percy exec -t 350 -- nx e2e ${{ matrix.project }} -c ci';
-            await exec.getExecOutput('bash', ['-c', percyCommand], { ignoreReturnCode: true })
-              .then((result) => {
-                if (result.exitCode !== 0) {
-                  if (
-                    result.stderr.includes('This is likely a client error') ||
-                    result.stderr.includes('Error: Can only finalize pending builds')
-                  ) {
-                    console.info('Percy client error. Retrying...');
-                    return exec.exec('bash', ['-c', percyCommand]);
-                  } else if (
-                    result.stderr.includes('AssertionError: Timed out retrying')
-                  ) {
-                    console.info('Cypress timeout error. Retrying...');
-                    return exec.exec('bash', ['-c', percyCommand]);
-                  } else {
-                    core.setFailed(`Percy failed with exit code ${result.exitCode}`);
-                  }
-                }
-              });
+        shell: bash
+        run: |
+          set +e
+
+          echo '# PERCY_TARGET_BRANCH' $PERCY_TARGET_BRANCH
+          echo '# PERCY_TARGET_COMMIT' $PERCY_TARGET_COMMIT
+
+          # Timing setting recommended by https://docs.percy.io/docs/cypress#missing-assets
+          npx percy exec -t 350 -- nx e2e ${{ matrix.project }} -c ci 2>&1 | tee ${{ runner.temp }}/percy.log
+          RESULT=$?
+          if [ $RESULT -ne 0 ]; then
+            echo "Percy failed with exit code $RESULT"
+            RETRY=$(grep -cE '(This is likely a client error|Error: Can only finalize pending builds)' ${{ runner.temp }}/percy.log)
+            if [ $RETRY -gt 0 ]; then
+              echo "Percy client error. Retrying..."
+              set -eo pipefail
+              npx percy exec -t 350 -- nx e2e ${{ matrix.project }} -c ci
+            else
+              exit 1
+            fi
+          fi
         env:
+          PERCY_TARGET_BRANCH: ${{ needs.install-deps.outputs.base-branch }}
+          PERCY_TARGET_COMMIT: ${{ steps.affected.outputs.percy_target_commit }}
           PERCY_TOKEN: ${{ secrets[matrix.token] }}
           TERM: 'xterm-256color'
         if: ${{ matrix.project != 'skip' && steps.affected.outputs.affected == 'true' }}
@@ -390,35 +393,42 @@ jobs:
       - uses: actions/github-script@v7
         name: Verify E2E Visual Review
         id: verify-e2e
+        if: ${{ always() }}
         with:
           github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
           script: |
 
-            const e2eProjects = ${{ needs.install-deps.outputs.parameters }}.e2eTargets.map(project => project.project);
-            const { verifyE2e } = require('./dist/libs/sdk/e2e-schematics/src/workflow');
+            const anyFailures = ${{ contains(needs.*.outcome, 'failure') }};
+            if (anyFailures) {
+              core.setFailed(`Job failed. Skipping visual review.`);
+            } else {
+              const e2eProjects = ${{ needs.install-deps.outputs.parameters }}.e2eTargets.map(project => project.project);
+              const { verifyE2e } = require('./dist/libs/sdk/e2e-schematics/src/workflow');
 
-            const options = {
-              method: 'GET',
-              headers: {
-                Authorization: 'Token ${{ secrets.PERCY_API }}'
-              }
-            };
+              const options = {
+                method: 'GET',
+                headers: {
+                  Authorization: 'Token ${{ secrets.PERCY_API }}'
+                }
+              };
 
-            await verifyE2e(
-              e2eProjects,
-              context.repo.owner,
-              context.repo.repo,
-              '${{ needs.install-deps.outputs.head }}',
-              '${{ github.run_id }}',
-              core,
-              {
-                listCommitStatusesForRef: github.rest.repos.listCommitStatusesForRef,
-                listJobsForWorkflowRun: github.rest.actions.listJobsForWorkflowRun
-              },
-              ${{ contains( fromJSON( needs.install-deps.outputs.pr-labels ), 'screenshot removed' ) }},
-              (url) => fetch(url, options),
-              (number) => process.exit(number)
-            );
+              await verifyE2e(
+                e2eProjects,
+                context.repo.owner,
+                context.repo.repo,
+                '${{ needs.install-deps.outputs.head }}',
+                '${{ github.run_id }}',
+                core,
+                {
+                  listCommitStatusesForRef: github.rest.repos.listCommitStatusesForRef,
+                  listJobsForWorkflowRun: github.rest.actions.listJobsForWorkflowRun
+                },
+                ${{ contains( fromJSON( needs.install-deps.outputs.pr-labels ), 'screenshot removed' ) }},
+                (url) => fetch(url, options),
+                (number) => process.exit(number)
+              );
+            }
+
       - name: Notify Slack (missing screenshots)
         if: ${{ failure() && steps.verify-e2e.outputs.missingScreenshots }}
         uses: rtCamp/action-slack-notify@v2
