ci: revert release please on 12.x.x

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -15,52 +15,58 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-        with:
-          token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
       - name: Next release
         if: ${{ env.PRERELEASE != 'false' }}
         id: next-release
-        shell: pwsh
         run: |
-          $validOptions = @("alpha", "beta", "rc")
-          if (-not $validOptions.Contains("${{ env.PRERELEASE }}")) {
-              Write-Error "Invalid PRERELEASE value. Must be 'alpha', 'beta', or 'rc'."
-              exit 1
-          }
+          # Log commands and exit on error.
+          set -exo pipefail
+
+          if [[ "${PRERELEASE}" != "alpha" && "${PRERELEASE}" != "beta" && "${PRERELEASE}" != "rc" ]]; then
+            echo "Invalid PRERELEASE value. Must be 'alpha', 'beta', or 'rc'."
+            exit 1
+          fi
 
           # Get the current prerelease version.
-          $ACC="Accept: application/vnd.github+json"
-          $VER="X-GitHub-Api-Version: 2022-11-28"
-          $JSON='map(.tag_name) | [.[] | select(startswith("${{ env.MAJOR_VERSION }}.")) ] | .[0] // empty'
-          $CURRENT_RELEASE=$(gh api -H "${ACC}" -H "${VER}" /repos/${{ github.repository }}/releases | jq -r "${JSON}")
+          ACC="Accept: application/vnd.github+json"
+          VER="X-GitHub-Api-Version: 2022-11-28"
+          JSON='map(.tag_name) | [.[] | select(startswith("${{ env.MAJOR_VERSION }}.")) ] | .[0] // empty'
+          CURRENT_RELEASE=$(gh api -H "${ACC}" -H "${VER}" /repos/${{ github.repository }}/releases | jq -r "${JSON}")
 
           # Bump the prerelease version.
-          if ( -not "$CURRENT_RELEASE" -or "$CURRENT_RELEASE" -notlike "${{ env.MAJOR_VERSION }}.0.0-${{ env.PRERELEASE }}.*" ) {
-            $NEXT_VERSION="${{ env.MAJOR_VERSION }}.0.0-${{ env.PRERELEASE }}.0"
-          } else {
-            $NEXT_VERSION=$(npx --yes semver -i prerelease $CURRENT_RELEASE)
-          }
+          if [[ -z "$CURRENT_RELEASE" || "$CURRENT_RELEASE" != "${{ env.MAJOR_VERSION }}.0.0-${{ env.PRERELEASE }}."* ]]; then
+            NEXT_VERSION="${{ env.MAJOR_VERSION }}.0.0-${{ env.PRERELEASE }}.0"
+          else
+            NEXT_VERSION=$(npx --yes semver -i prerelease $CURRENT_RELEASE)
+          fi
 
           # If version is empty, exit.
-          if ( -not "$NEXT_VERSION" ) {
+          if [ -z "$NEXT_VERSION" ]; then
             echo "Not able to determine prerelease version."
             exit 1
-          }
+          fi
 
           echo "Next release version: $NEXT_VERSION"
-
-          $configFilePath = "release-please-config.json"
-          $configFile = Get-Content $configFilePath -Raw | ConvertFrom-Json
-          $configFile."release-as" = "$NEXT_VERSION"
-          $configFile.prerelease = $True
-          $configFile | ConvertTo-Json -Depth 10 | Set-Content $configFilePath
+          echo "next-release=$NEXT_VERSION" >> $GITHUB_OUTPUT
         env:
           GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
-      - uses: googleapis/release-please-action@v4
+      - uses: google-github-actions/release-please-action@v3
         id: release
         with:
-          target-branch: '${{ github.ref_name }}'
+          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"deprecation","section":"Deprecations","hidden":false},{"type":"revert","section":"Reverts","hidden":false}]'
+          release-type: 'node'
+          default-branch: '${{ github.ref_name }}'
+          package-name: 'skyux'
+          pull-request-title-pattern: 'chore: release ${version}'
+          labels: 'autorelease ${{ github.ref_name }}: pending'
+          release-labels: 'autorelease ${{ github.ref_name }}: tagged'
+          release-as: '${{ steps.next-release.outputs.next-release }}'
+          prerelease: ${{ env.PRERELEASE != 'false' }}
+          draft-pull-request: true
+          include-v-in-tag: false
+          token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
+      - uses: actions/checkout@v4
+        with:
           token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
       - uses: actions/setup-node@v4
         id: setup-node
